name: Maven CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Set up ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-chromedriver
        sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver

    - name: Running Automation tests with Maven
      run: mvn test -X -Dbrowser=chrome -DisLambdaTest=false -DisHeadless=true

    - name: Create extent-reports directory and copy files
      run: |
        mkdir -p public/extent-reports
        cp -R report.html public/extent-reports/
        if [ -d "screenshots" ]; then
          cp -R screenshots public/extent-reports/screenshots
        fi
        ls -l
      shell: bash

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: public/extent-reports
        token: ${{ secrets.GITHUB_TOKEN }}
        clean: true
        branch: gh-pages
        force: true
