name: Test Automation Framework

on:
  schedule:
  - cron: 00 18 * * *
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      TEST_DATA_PATH: '/home/runner/work/AutomationFramework/testData'
      
    steps:
    - name: checkout code
      uses: actions/checkout@v2
      with:
        ref: master
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Running Automation tests with Maven
      run: |
        mvn test -X \
          -Dbrowser=chrome \
          -DisLambdaTest=true \
          -DisHeadless=false \
          -Dtest.data.path=${{ env.TEST_DATA_PATH }}

    - name: Upload Test Logs
      if: always()
      uses: actions/upload-artifact@v4.4.3
      with:
        name: Test Logs
        path: logs/


    - name: Upload Reports Logs
      if: always()
      uses: actions/upload-artifact@v4.4.3
      with:
        name: Test Reports
        path: reports.html

    - name: Test Execution Status
      run: echo "Test Execution Completed"

