name: Test Automation Framework

on:
  schedule:
  - cron: 00 18 * * *
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v3
      with:
        ref: master
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Running Automation tests with Maven
      run: mvn test -X -Dbrowser=chrome -DisLambdaTest=true -DisHeadless=false

    - name: Upload Test Logs
      if: always()
      uses: actions/upload-artifact@v4.4.3
      with:
        name: Test Logs
        path: logs/


    - name: Upload Reports Logs
      if: always()
      uses: actions/upload-artifact@v4.4.3
      with:
        name: Test Reports
        path: reports.html

    - name: Test Execution Status
      run: echo "Test Execution Completed"

